--- #Playbook to do susyem update using Yum

- hosts: upgrade
  gather_facts: no
  become: yes

  tasks:
    - name : Update System Packages
      yum : name=* state=latest

    - name : Check if reboot is required
      shell : LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
      ignore_errors: true
      register: reboot_hint

    - name: Rebooting ......
      command: /sbin/shutdown -r +1 " Rebooting after kernel update"
      async: 0
      poll: 0
      ignore_errors: true
      when: reboot_hint.stdout.find("reboot") != -1
      register: rebooting

    - name: Waiting for server to reboot...
      pause: seconds=120
      when: rebooting|changed

    - name: Check server uptime
      command: uptime
      register: time
    - debug: uptime=time
